services:
  sensor-container:
    image: samisauchda/sensor-container:latest

    container_name: sensor-container
    restart: unless-stopped

    volumes:
      # Mount your custom config file to override the default
      - ./config.yml:/app/config.yml

    # Uncomment if you need GPIO access on Raspberry Pi
    # devices:
    #   - /dev/gpiomem:/dev/gpiomem
    # privileged: true
