services:
  sensor-container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sensor-container
    restart: unless-stopped
    volumes:
      - ./app:/app
    environment:
      MQTT_BROKER: "localhost"
      MQTT_PORT: "1883"
      DEVICE_NAME: "Living Room Sensor"
