services:
  sensor-container:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sensor-container
    restart: unless-stopped
    volumes:
      - ./app:/app
      - ./config.yml:/app/config.yml