mqtt:
  broker: "localhost"
  port: 1883
  username: ""
  password: ""
  topic: "office/simulated/sensor1"

device:
  name: "sim01"

sensor:
  update_interval: 60        # Sekunden
  temperature_min: 20.0
  temperature_max: 28.0
  humidity_min: 40.0
  humidity_max: 60.0
